services:
  portainer-ce:
    image: portainer/portainer-ce:linux-amd64
    container_name: portainer-ce-linux-amd64
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    privileged: true