services:

  mongo:
    image: mongo:latest
    container_name: mongo-latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1123581321345589
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
      - ./data/log:/var/log/mongodb
      - ./data/config:/etc/mongo

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-latest 
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1123581321345589
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 1123581321345589