services:
  redis-sentinel1:
    container_name: redis-sentinel1
    image: redis:7.2-bookworm
    volumes:
      - ./sentinel/sentinel1/conf:/etc/redis
      - ./sentinel/sentinel1/data:/data
    restart: always
    ports:
      - "26479:26379"
    privileged: true
    command: redis-sentinel /etc/redis/sentinel.conf
    depends_on:
      - redis-master
  
  redis-sentinel2:
    container_name: redis-sentinel2
    image: redis:7.2-bookworm
    volumes:
      - ./sentinel/sentinel2/conf:/etc/redis
      - ./sentinel/sentinel2/data:/data
    restart: always
    ports:
      - "26579:26379"
    privileged: true
    command: redis-sentinel /etc/redis/sentinel.conf
    depends_on:
      - redis-master
  
  redis-sentinel3:
    container_name: redis-sentinel3
    image: redis:7.2-bookworm
    volumes:
      - ./sentinel/sentinel3/conf:/etc/redis
      - ./sentinel/sentinel3/data:/data
    restart: always
    ports:
      - "26679:26379"
    privileged: true
    command: redis-sentinel /etc/redis/sentinel.conf
    depends_on:
      - redis-master

  redis-master:
    container_name: redis-master
    image: redis:7.2-bookworm
    volumes:
      - ./server/master/conf:/etc/redis
      - ./server/master/data:/data
    restart: always
    ports:
      - "6379:6379"
    privileged: true
    command: redis-server /etc/redis/redis.conf
  
  redis-slave1:
    container_name: redis-slave1
    image: redis:7.2-bookworm
    volumes:
      - ./server/slave1/conf:/etc/redis
      - ./server/slave1/data:/data
    restart: always
    ports:
      - "6479:6379"
    privileged: true
    command: redis-server /etc/redis/redis.conf --replicaof redis-master 6379
    depends_on:
      - redis-master

  redis-slave2:
    container_name: redis-slave2
    image: redis:7.2-bookworm
    volumes:
      - ./server/slave2/conf:/etc/redis
      - ./server/slave2/data:/data
    restart: always
    ports:
      - "6579:6379"
    privileged: true
    command: redis-server /etc/redis/redis.conf --replicaof redis-master 6379
    depends_on:
      - redis-master