services:
  nacos1:
    hostname: nacos1
    container_name: nacos-2.2.3-1
    image: nacos/nacos-server:v2.2.3
    env_file:
      - ./env/cluster.env
    volumes:
      - ./nacos1/log/:/home/nacos/logs
      - ./nacos1/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "7848:7848"
      - "8848:8848"
      - "9848:9848"
      - "9850:9849"
    restart: unless-stopped
    privileged: true
    stdin_open: true
    tty: true

  nacos2:
    hostname: nacos2
    container_name: nacos-2.2.3-2
    image: nacos/nacos-server:v2.2.3
    env_file:
      - ./env/cluster.env
    volumes:
      - ./nacos2/log/:/home/nacos/logs
      - ./nacos2/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "7849:7848"
      - "8849:8848"
      - "9869:9848"
      - "9851:9849"
    restart: unless-stopped
    privileged: true
    stdin_open: true
    tty: true

  nacos3:
    hostname: nacos3
    container_name: nacos-2.2.3-3
    image: nacos/nacos-server:v2.2.3
    env_file:
      - ./env/cluster.env
    volumes:
      - ./nacos3/log/:/home/nacos/logs
      - ./nacos3/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "7850:7848"
      - "8850:8848"
      - "9870:9848"
      - "9852:9849"
    restart: unless-stopped
    privileged: true
    stdin_open: true
    tty: true