services:
  nginx:
    container_name: nginx-1.25.2-bookworm
    image: nginx:1.25.2-bookworm
    volumes:
      - ./conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf:/etc/nginx/conf
      - ./html:/usr/share/nginx/html
      - ./logs:/var/log/nginx
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
    restart: unless-stopped
    privileged: true
    stdin_open: true
    tty: true