services:
  redis-master:
    container_name: redis-master
    image: redis:7.2.0-bookworm
    volumes:
      - ./master/conf/redis.conf:/etc/redis/redis.conf
      - ./master/data:/data
    restart: always
    ports:
      - "6379:6379"
    privileged: true
    command: redis-server /etc/redis/redis.conf
  
  redis-slave1:
    container_name: redis-slave1
    image: redis:7.2.0-bookworm
    volumes:
      - ./slave1/conf/redis.conf:/etc/redis/redis.conf
      - ./slave1/data:/data
    restart: always
    ports:
      - "6380:6379"
    privileged: true
    command: redis-server /etc/redis/redis.conf --replicaof redis-master 6379
    depends_on:
      - redis-master

  redis-slave2:
    container_name: redis-slave2
    image: redis:7.2.0-bookworm
    volumes:
      - ./slave2/conf/redis.conf:/etc/redis/redis.conf
      - ./slave2/data:/data
    restart: always
    ports:
      - "6381:6379"
    privileged: true
    command: redis-server /etc/redis/redis.conf --replicaof redis-master 6379
    depends_on:
      - redis-master